### ISSUE TITLE
Notify users about prediction market resolution

### ISSUE THREAD

**Issue by Georgi87** [protofire/gnosis-conditional-exchange#142]
Use the notifications API (https://developer.mozilla.org/en-US/docs/Web/API/Notifications_API/Using_the_Notifications_API) to ping users once a market is resolved and the user can redeem their winnings. Only notify users, who participated in this market.

Open question: Can this be done without a backend component?

**Comment by leolower** [comment]
Research here: https://hackmd.io/8WXMUAp9QPymkQGRjO_bfQ

**Comment by leolower** [comment]
Postponed for now.
