### ISSUE TITLE
List markets UI

### ISSUE THREAD

**Issue by leolower** [protofire/gnosis-conditional-exchange#152]
This initial version will only show basic information and link to market page. It will not have pagination and it will not be very performant when loading many markets.

Each market should include:
- Question / market name
- Resolution date
- Status (open / resolved)

**Comment by leolower** [comment]
@gabitoesmiapodo we updated the ticket description to include the information we want to show for each market.

**Comment by gabitoesmiapodo** [comment]
This was implemented on https://github.com/protofire/gnosis-conditional-exchange/pull/166

**Comment by mariano-aguero** [comment]
PR closed
