### ISSUE TITLE
Create a design for the MarketNotFound component

### ISSUE THREAD

**Issue by mariano-aguero** [protofire/gnosis-conditional-exchange#169]
Now look like this..
![Screenshot_20191108_113156](https://user-images.githubusercontent.com/1144028/68484438-04238d00-021c-11ea-98e5-b307bba302a2.png)

**Comment by gabitoesmiapodo** [comment]
OK, remind me to do something about this.

**Comment by gabitoesmiapodo** [comment]
Here: https://app.zeplin.io/project/5b71fb9cd86c791b1612c035/screen/5dcf19f6f124fd44ded2fb18
