### ISSUE TITLE
Refactor code to easily allow for adding new oracles as replacement for realit.io

### ISSUE THREAD

**Issue by Georgi87** [protofire/gnosis-conditional-exchange#189]
Other oracle providers would like to integrate with this product. For this, it would be nice to have a lose coupling with realit.io and be able to swap it with another oracle on code level.

**Comment by fvictorio** [comment]
So, we've been thinking about this, and there are several approaches to do it.

Probably the easiest one is for other oracles to implement the same interface as the Realitio contract (the `askQuestion` method and the `LogNewQuestion` event). Then the app would have a dropdown to select the oracle. This would require much less work on our side but it's not very flexible for oracles implementers.

Another option is to abstract how we post new questions and how we get already posted questions, and also to adapt the UI to remove explicit mentions to Realitio (changing them for the name of the selected oracle). This is more flexible and doesn't imply many changes in the code, but oracles would need to have a similar model to Realitio's: a question, a resolution date, an event emitted when a new question is created, a `bytes32 questionId` to use in the `ConditionalTokens` contract, etc.

Finally, we could support any kind of oracles even if they don't adhere to how Realitio creates questions. I'm not sure how this would work, but at the very least it would mean making specific screens for each oracle. So, it's the more flexible approach but also the one that would take the longest time.
