### ISSUE TITLE
Show error message when opening market details without wallet connected

### ISSUE THREAD

**Issue by leolower** [protofire/gnosis-conditional-exchange#205]
- Don't allow to enter market detail screen without web3 provider (currently shows empty page)

**Comment by gabitoesmiapodo** [comment]
You can grab a few sample alerts from here: https://zpl.io/bL1vd07

![07 - Conditional Exchange - Alert](https://user-images.githubusercontent.com/4015436/69182844-95ceac80-0af0-11ea-9a56-b07001c4a4c9.png)
