### ISSUE TITLE
Market list infinite scroll

### ISSUE THREAD

**Issue by leolower** [protofire/gnosis-conditional-exchange#210]

**Comment by gabitoesmiapodo** [comment]
Infinite scroll design is here https://zpl.io/am7P7RQ

It should be possible to grab an SVG file for the loading placeholders.

![13 - Conditional Exchange - List](https://user-images.githubusercontent.com/4015436/69183008-dfb79280-0af0-11ea-828b-72ca5a57d5b1.png)
