### ISSUE TITLE
Ability to create multiple options on Market creation

### ISSUE THREAD

**Issue by leolower** [protofire/gnosis-conditional-exchange#212]
**Design:** We need to update this section's design to provide a better way of adding multiple options / outcomes.

There's a preliminary design, but I think it could be improved.

Maybe there's a better place for the `+` button?

Also add a scroll for the items' list.

**Note:** This issue includes design for #213 

![03 - Conditional Exchange - Create 3](https://user-images.githubusercontent.com/4015436/70629485-d52c7c80-1c08-11ea-94dd-b126598692bf.png)

**Comment by gabitoesmiapodo** [comment]
@alongoni add your updates here.

**Comment by alongoni** [comment]
![03 - Conditional Exchange - Create 3 – Multiple Outcomes](https://user-images.githubusercontent.com/622217/70918116-57e47b80-1ffd-11ea-9462-e95b49571136.png)

Issue #213 
![03 - Conditional Exchange - Create 3 – Multiple Outcomes – 1](https://user-images.githubusercontent.com/622217/70918115-57e47b80-1ffd-11ea-9f37-661810872b2c.png)

**Comment by gabitoesmiapodo** [comment]
Looks good.

Maybe the `Total outcomes / 120%` part gets a little lost? We should find a way to differentiate it a little more. Maybe separate it from the "Add new possible outcome" with some margin, and / or remove the dark gray background.

Not sure, but maybe put the result (`Total outcomes / 120%`) at the bottom end?

Also, text should be "Add new outcome"

**Comment by alongoni** [comment]
![03 - Conditional Exchange - Create 3 – Multiple Outcomes a](https://user-images.githubusercontent.com/622217/70922518-fc1df080-2004-11ea-83fa-3ec6cc8b26f3.png)

Variant: total outcomes at the end:
![03 - Conditional Exchange - Create 3 – Multiple Outcomes -total end](https://user-images.githubusercontent.com/622217/70922516-fc1df080-2004-11ea-8fdd-abd3e96ff64c.png)


![03 - Conditional Exchange - Create 3 – Multiple Outcomes – 1](https://user-images.githubusercontent.com/622217/70922517-fc1df080-2004-11ea-8618-1e46dce17fa5.png)

**Comment by gabitoesmiapodo** [comment]
Looks good, this one's OK

![03 - Conditional Exchange - Create 3 – Multiple Outcomes a](https://user-images.githubusercontent.com/622217/70922518-fc1df080-2004-11ea-83fa-3ec6cc8b26f3.png)

You can discard the other one.

Good job.
