### ISSUE TITLE
Update confirmation page

### ISSUE THREAD

**Issue by leolower** [protofire/gnosis-conditional-exchange#216]
**Design:** We need to update this section to support a list of more than 2 options / outcomes.

Also check if we need to change the order of subsections to make it more consistent with the rest (ie: "Outcomes" first, then "Details", etc.)

Maybe the info / warning should be at the bottom too?

![05 - Conditional Exchange - Show URL](https://user-images.githubusercontent.com/4015436/70635429-aa472600-1c12-11ea-9b82-ea67313d3d68.png)

**Comment by alongoni** [comment]
- Add a scroll area for multiple outcomes/options.
- The order of subsections present no changes. They maintain the market creation steps. It is important that the user first see the details and then the options.
- Message / info look fine at the top.
![05 - Conditional Exchange - Show URL](https://user-images.githubusercontent.com/622217/71004809-3a78e580-20c1-11ea-9956-68aaefa209a9.png)

**Comment by gabitoesmiapodo** [comment]
Looks good.
