### ISSUE TITLE
Update summary page

### ISSUE THREAD

**Issue by leolower** [protofire/gnosis-conditional-exchange#217]
**Design:** We need to update this section to support a list of more than 2 options / outcomes.

Also check if we need to change the order of subsections to make it more consistent with the rest (ie: "Outcomes" first, then "Details", etc.)

Maybe the info / warning should be at the bottom too?

![04 - Conditional Exchange - Create 4](https://user-images.githubusercontent.com/4015436/70635283-69e7a800-1c12-11ea-9494-3e48cd38c154.png)

**Comment by alongoni** [comment]
- Add a scroll area for multiple outcomes/options.
- The order of subsections present no changes. They maintain the market creation steps. It is important that the user first see the details and then the options.
- Message / info look fine at the top.  

![04 - Conditional Exchange - Create 4](https://user-images.githubusercontent.com/622217/71002653-80807a00-20be-11ea-8a8c-e773ce87f90e.png)

**Comment by gabitoesmiapodo** [comment]
Looks good.
