### ISSUE TITLE
CATEGORICAL MARKETS - Market details - List all options

### ISSUE THREAD

**Issue by leolower** [protofire/gnosis-conditional-exchange#219]
**Development:** List all options.

**Design:** It should be possible to list more than two options, but I think the list shouldn't grow indefinitely. Maybe limit the list to 4 elements and show a scroll bar from then on.

![Screen Shot 2019-12-11 at 09 44 20](https://user-images.githubusercontent.com/4015436/70622747-5715a900-1bfb-11ea-842b-873e0b4d6746.png)

**Comment by alongoni** [comment]
Add scroll bar for multiple outcomes. 
![08 - Conditional Exchange - Overview - Balance](https://user-images.githubusercontent.com/622217/71087641-71abcd00-217b-11ea-9b9c-2d177c42ab5b.png)

**Comment by gabitoesmiapodo** [comment]
Looks good, I have nothing to complain about.
