### ISSUE TITLE
CATEGORICAL MARKETS - Fund existing market - List all options

### ISSUE THREAD

**Issue by leolower** [protofire/gnosis-conditional-exchange#222]
**Design:** This section needs an update. It's implemented but there's no design, so add a new one. We need to make it look more like the others.

**Some thoughts:**

- Maybe "Amount" should be first? It's the most important thing on this section. Maybe the buttons should be near it? Not sure about this.

- If we don't put "Amount" first, we should follow the order we followed on the other sections: "Outcomes" first, then "Details" (we need to make "Details" look like on the other designs BTW...), and "Amount" last.

- Maybe the wording and order for the buttons should be "Remove Funds" / "Fund".

![Screen Shot 2019-12-11 at 09 52 51](https://user-images.githubusercontent.com/4015436/70623401-cdff7180-1bfc-11ea-9fb8-7818c9b4c113.png)

**Comment by alongoni** [comment]
- I made changes based on structure of Buy/Sell screen. 
- Change button text and order.

![09 - Conditional Exchange - Fund](https://user-images.githubusercontent.com/622217/71097778-55199000-218f-11ea-8230-a64ad878a5f7.png)

**Comment by gabitoesmiapodo** [comment]
- I've been using the "Full" buttons version for "final" actions (for example "Create", "Finish", "Save", etc.), and the "Line" version for intermediate actions ("Next", etc.).

I think we should use the full version for "Remove Funding" and "Fund" to keep consistency, and use the orange version for "Remove Funding" to differentiate the buttons, and also to indicate certain "danger" in performing this action.

- You should add the scroll for multiple options at the top.

- The four items at the beginning of the original screenshot are fixed ("Total funding", etc.), so they all should be present in your design.

**Comment by alongoni** [comment]
![09 - Conditional Exchange - Fund](https://user-images.githubusercontent.com/622217/71176402-91f58d80-2248-11ea-83fa-82482cab2b19.png)

**Comment by gabitoesmiapodo** [comment]
Nice.
