### ISSUE TITLE
See my collateral balance and max link

### ISSUE THREAD

**Issue by mariano-aguero** [protofire/gnosis-conditional-exchange#238]
This task is for UI design, to improve the actual behaviour.

**Comment by mariano-aguero** [comment]
See tickets #195 and #196

**Comment by gabitoesmiapodo** [comment]
`Max` button is here: https://zpl.io/aRXnx8N

![02 - Conditional Exchange - Create 2](https://user-images.githubusercontent.com/4015436/70467051-43572f00-1aa3-11ea-858a-108a52536049.png)

**Comment by gabitoesmiapodo** [comment]
`Max` buttons for two more sections: https://zpl.io/a8J8716 - https://zpl.io/aRXnx5v

![09 - Conditional Exchange - Buy](https://user-images.githubusercontent.com/4015436/70468832-8e267600-1aa6-11ea-95a7-4089e86d621a.png)
![10 - Conditional Exchange - Sell](https://user-images.githubusercontent.com/4015436/70468834-8ebf0c80-1aa6-11ea-8f01-9ab474498c32.png)
