### ISSUE TITLE
Bar diagram for current probabilities, improve design

### ISSUE THREAD

**Issue by mariano-aguero** [protofire/gnosis-conditional-exchange#249]
See #203

**Comment by gabitoesmiapodo** [comment]
Updated the designs, have a look.

![16 - Conditional Exchange - Probabilities Bars](https://user-images.githubusercontent.com/4015436/70622175-1c5f4100-1bfa-11ea-82df-0256cf197f5f.png)

![16 - Conditional Exchange - Details](https://user-images.githubusercontent.com/4015436/70622195-2a14c680-1bfa-11ea-81ac-19ce0e5bea22.png)
![08 - Conditional Exchange - Overview : Balance](https://user-images.githubusercontent.com/4015436/70622197-2aad5d00-1bfa-11ea-8096-7650610c7dd5.png)
![09 - Conditional Exchange - Buy](https://user-images.githubusercontent.com/4015436/70622198-2aad5d00-1bfa-11ea-8da4-7076e77ed672.png)
![10 - Conditional Exchange - Sell](https://user-images.githubusercontent.com/4015436/70622199-2aad5d00-1bfa-11ea-82e3-fc8eed89ce36.png)
![11 - Conditional Exchange - Redeem : Closed Market](https://user-images.githubusercontent.com/4015436/70622200-2aad5d00-1bfa-11ea-9b7a-9333307d86d4.png)
![12 - Conditional Exchange - Withdraw Collateral](https://user-images.githubusercontent.com/4015436/70622201-2b45f380-1bfa-11ea-9aac-42ffe0b400d0.png)
