### ISSUE TITLE
Design for the "Add Collateral" / "Collateral modal"

### ISSUE THREAD

**Issue by mariano-aguero** [protofire/gnosis-conditional-exchange#266]
**Design**:  

- Step 2's design needs an update to better accommodate the "Add Collateral" button.
- There's also a new modal window to add the collateral, and it needs a design too.

Both are already implemented.

**Some thoughts:**

- Maybe add the `+` button as a link (check the "Add funds" link in other sections).
- The details data in the modal can be really long sometimes, beware of that.
- Use the "Connect to wallet" modal (see below) as a starting point for the new modal.

**Step 2's current implementation**

![Screenshot_20191211_095017.png](https://images.zenhubusercontent.com/5d70fed5c5574a4392cc4047/a7b8384c-472b-43d9-9f4b-e45b4639801f)

**Modal's current implementation:**

![Screenshot_20191211_095025.png](https://images.zenhubusercontent.com/5d70fed5c5574a4392cc4047/2182eb6f-6c69-4be3-9435-0804933fcf6d)

**Connect to Wallet Modal:**

![15 - Conditional Exchange - Select Wallet](https://user-images.githubusercontent.com/4015436/70630194-ef1a8f00-1c09-11ea-9d99-ce782f628035.png)

**Comment by alongoni** [comment]
Updated design: Add collateral link button - modal windows
![02 - Conditional Exchange - Create 2](https://user-images.githubusercontent.com/622217/70729375-dda4b600-1ce1-11ea-87d4-6b14c3635253.png)
![02 Modal - Conditional Exchange - Create 2](https://user-images.githubusercontent.com/622217/70729376-de3d4c80-1ce1-11ea-9daa-0c5a90677572.png)

**Comment by gabitoesmiapodo** [comment]
Looks good.

A few suggestions for the modal:

- Title should be just "Add Collateral", or "Add New Collateral". Also, capitalize long words for titles.
- Title for the input field should be something like "Collateral Token Address" with any further indications or tips in the placeholder's text (for example: "Paste a valid address...").
- Horizontal padding seems to be too big, check if it's the same as in the "Connect to wallet" modal (not sure about this one).
- The wording for the button should be "Add" or something more appropriate. Think of something related to the action you are going to perform.
- The button's width seems to be wrong, it should occupy all the available width minus the window's horizontal padding.
- Check with @mariano-aguero or @fvictorio what data are we going to show for `Symbol`, and `Decimals`, and add it to the design. It makes not sense to have those labels and no data.
- Related to the last item: add a note saying that we shouldn't show that part until we load the data. We shouldn't show info we don't have.
- We're missing a few possible states: Loading (add a spinner were the data is going to be), Error / Couldn't load data (think were to show this, check if there's something already in the designs or on the app).

**Comment by mariano-aguero** [comment]
Hi @alongoni , looks pretty good.
In this link you can see a lot of tokens and its symbol: https://etherscan.io/tokens
You can check  how it looks with data and with an error message right [here](https://imgur.com/a/ev0rfC8)

Sorry, github doesn't love me and I can't upload images.

**Comment by alongoni** [comment]
Well, I make a few changes. In this screen, the placeholder text is a generic/simulated token address (like when we complete an input field with a email, a simple method).
![02 - Conditional Exchange - Create - Modal Add Collateral](https://user-images.githubusercontent.com/622217/70821618-4a8b7f00-1dba-11ea-9e40-039d8d4920f0.png)

Here, when a token address is invalid or wrong, appear a red message and the ADD button turn on disable.
![02 - Conditional Exchange - Create - Modal Add Collateral – Invalid token](https://user-images.githubusercontent.com/622217/70822148-97bc2080-1dbb-11ea-8998-a42d718e7a62.png)

Finally, if the token address is valid, the app load more info and details.
![02 - Conditional Exchange - Create - Modal Add Collateral – Success](https://user-images.githubusercontent.com/622217/70822382-292b9280-1dbc-11ea-95ec-9b82e5f6bc79.png)

**Comment by gabitoesmiapodo** [comment]
That's better.

A few more issues:

- Check the error's color, make it look less orange-ish and more red-ish to avoid confusion with the app's orange already in use.
- Make `Symbol` and `Decimals` bold, and the data normal, just to make it look like the rest of the app.

**Comment by alongoni** [comment]
![02 - Conditional Exchange - Create - Modal Add Collateral – Invalid token](https://user-images.githubusercontent.com/622217/70904098-52783880-1fdf-11ea-81e6-e1caea979aa4.png)
![02 - Conditional Exchange - Create - Modal Add Collateral – Success](https://user-images.githubusercontent.com/622217/70904099-5310cf00-1fdf-11ea-9f88-35a48ac2e820.png)

**Comment by gabitoesmiapodo** [comment]
@alongoni Looks great, let's move on to the next one.
