### ISSUE TITLE
UI Design

### ISSUE THREAD

**Issue by leolower** [protofire/gnosis-conditional-exchange#27]
Initial wireframes: https://docs.google.com/presentation/d/1cSss6f2m5gJgilC_DJr_nVv2BWDtoVTWnKSsdUX1wy0/edit#slide=id.g5f14fe4b00_0_0

**Comment by gabitoesmiapodo** [comment]
Design is here https://drive.google.com/open?id=12ff4PNRnatX1Sr5RzrvTae0m2KFcUUsC
