### ISSUE TITLE
Select wallet and use WalletConnect

### ISSUE THREAD

**Issue by mariano-aguero** [protofire/gnosis-conditional-exchange#29]

**Comment by mariano-aguero** [comment]
We need to improve the design of the buttons we use to connect

**Comment by gabitoesmiapodo** [comment]
OK, I'll do it ASAP.

**Comment by gabitoesmiapodo** [comment]
These can be used:

1- Connect button: https://app.zeplin.io/project/5b71fb9cd86c791b1612c035/screen/5dcf19f6f124fd44ded2fb18

2- Select wallet https://app.zeplin.io/project/5b71fb9cd86c791b1612c035/screen/5dcf19f705dced45389d3574
