### ISSUE TITLE
Add option to logout from the current wallet

### ISSUE THREAD

**Issue by leolower** [protofire/gnosis-conditional-exchange#291]
We need a button or link to let the user logout from the current wallet.

I'll leave the details and workflow up to you.

**Comment by alongoni** [comment]
![18 - Conditional Exchange - Disconect wallet](https://user-images.githubusercontent.com/622217/71266238-c3448b00-2326-11ea-90be-5481e2a83a8d.png)
![18b - Conditional Exchange - Disconect wallet – 1](https://user-images.githubusercontent.com/622217/71266239-c3dd2180-2326-11ea-9ae0-a552c2e30d32.png)
![18c - Conditional Exchange - Disconect wallet - Error](https://user-images.githubusercontent.com/622217/71266240-c3dd2180-2326-11ea-8026-13e93f8bd4b0.png)
![18d - Conditional Exchange - Disconect wallet - Succes](https://user-images.githubusercontent.com/622217/71266241-c3dd2180-2326-11ea-9d8e-93c656d8f1a4.png)

**Comment by gabitoesmiapodo** [comment]
Looks nice, but I'm not sure if we need a dropdown for only one option

@fvictorio @mariano-aguero  opinions?

Also the icon is kind of weird?

**Comment by mariano-aguero** [comment]
> Looks nice, but I'm not sure if we need a dropdown for only one option
> 
> @fvictorio @mariano-aguero opinions?
> 
> Also the icon is kind of weird?

Mmmm a simple button will be fine for me, and yes, the icon is weird and maybe at first sight  it's not very user friendly (what it means?  what it do ? )

**Comment by alongoni** [comment]
Some options:
1 - Disconnect icon + tooltip
2- Disconnect button
3 - Another icon + tooltip
@gabitoesmiapodo @mariano-aguero 
![17 - Disconnect wallet](https://user-images.githubusercontent.com/622217/71473345-5cefba80-27b5-11ea-9381-d40c53e82f37.png)

**Comment by gabitoesmiapodo** [comment]
I'm not fully convinced by any of those.

In the 2nd, is green an OK color to indicate something will disconnect?

For the 3rd, I'm fine with the icon, but I'm not sure it looks like something you would click (I mean, it doesn't look like a button).

@mariano-aguero thoughts?

**Comment by mariano-aguero** [comment]
> I'm not fully convinced by any of those.
> 
> In the 2nd, is green an OK color to indicate something will disconnect?
> 
> For the 3rd, I'm fine with the icon, but I'm not sure it looks like something you would click (I mean, it doesn't look like a button).
> 
> @mariano-aguero thoughts?

Mmmm I have many doubts about it. The two icons do not convince me. If we have a button to connect  the most logical thing for a user is to expect to have a button to disconnect. Maybe with other color warning the user. I think that if we are going to use an icon you should use something similar to connect (we use a button) and it should be representative of the action to be performed. 
How those icons should be? I have no idea, maybe we could see how other applications solve it. I'm better with the second options for now

**Comment by gabitoesmiapodo** [comment]
@mariano-aguero Yeah, agreed.

@alongoni please have a look when you have the time.

**Comment by alongoni** [comment]
OK, take a look. 
Thanks! @gabitoesmiapodo @mariano-aguero 
![17 - Conditional Exchange - Disconect wallet](https://user-images.githubusercontent.com/622217/71514692-aeb04780-287e-11ea-8caf-af76faa659fc.png)

**Comment by gabitoesmiapodo** [comment]
Looks fine.
