### ISSUE TITLE
Improve information shown in buy page

### ISSUE THREAD

**Issue by fvictorio** [protofire/gnosis-conditional-exchange#304]
Right now the Buy page looks like this:

![image](https://user-images.githubusercontent.com/417134/71485817-d5746c80-27f1-11ea-86be-b041bba01892.png)

But the "You spend" part is wrong: if the user enters 1.00 DAI, then they'll spend 1.00 DAI, not 1.04. 0.96 of those DAIs will be exchanged by outcome tokens and 0.04 will be kept as fee.

I think just fixing this by showing 1.00 won't work, because it won't be adding relevant information. Changing it for 0.96 might be better but is perhaps misleading: you won't spend 0.96; you'll spend 1.00.

**Comment by mariano-aguero** [comment]
This is a proposal for this, @alongoni do you have any suggestions for this problem ? 

```
Amount: 2DAI

.
.
.

COSTS

1.5% Trade Fee........... -0.03 DAI
Final Amount ............. 1.97 DAI

SHARES

"X" Shares ................ 2.65 shares
```

**Comment by gabitoesmiapodo** [comment]
@alongoni I have some ideas for this, let me know when you start working on it.

**Comment by alongoni** [comment]
After a few iterations with gabito, we get this:
![10c  - Conditional Exchange - Buy – 2](https://user-images.githubusercontent.com/622217/71844194-6aa21b80-30a4-11ea-910a-873e1b1c619c.png)

**Comment by cag** [comment]
Hmm, wdyt about

Base cost: 1.97 DAI
Trading fee: 0.03 DAI
Total cost: 2 DAI (user input)
You will receive 7.03 shares

**Comment by alongoni** [comment]
Thanks @cag ! 
I´m not sure about wording: "Total cost". Is it correct?
[10c  - Conditional Exchange - Buy – 2](https://user-images.githubusercontent.com/622217/72011267-36f7fa80-3238-11ea-848d-4880c4e55670.png)

**Comment by fvictorio** [comment]
FWIW I think this is enough. Wording can be changed later. The important part is how the numbers are presented, and I think this last design is clear enough.

**Comment by mariano-aguero** [comment]
Design is right here ... https://app.zeplin.io/project/5b71fb9cd86c791b1612c035/screen/5e188062a6932b7cb606ff1b
