### ISSUE TITLE
Error when logging out

### ISSUE THREAD

**Issue by gabitoesmiapodo** [protofire/gnosis-conditional-exchange#308]
If you logout when creating a market, you'll get a blank screen.

Steps:

- Login.
- Go to "Create Market"
- Logout (which step doesn't seem to matter).

The app should logout correctly, but you'll get a blank screen. This doesn't seem to happen when you are doing something on other sections.

If you refresh, the app will look OK, but there's no content besides the footer and header (and no info messages).

Maybe the user should be redirected to the "Markets Overview" section when this happens?

**Comment by mariano-aguero** [comment]
Hi @gabitoesmiapodo I was doing some tests in the branch `milestone-5`, and apparently the problem was already solved, feel free to reopen the issue in case it reappears.
