### ISSUE TITLE
Show price after trade by adjusting the probability bars

### ISSUE THREAD

**Issue by fvictorio** [protofire/gnosis-conditional-exchange#310]
Instead of showing a column with the price after trade, adjust the bars to reflect this new probability.

Sight does this already. It also shows the change in percentage, but let's leave that for another issue.

Sight: https://drive.google.com/open?id=1rQs-ovKNSyfjwskjRH6GpSZXAI8OUpbQ

**Comment by mariano-aguero** [comment]
@gabitoesmiapodo Do you think this issue needs some design? I think not, but I want to check it with you. 

Regards

**Comment by gabitoesmiapodo** [comment]
From what I understand, it could be done with what we already have, but I could be wrong.

If it's only changing the percentage's value and the bars' progress I think you don't need anything else. Maybe just animate the progress when it changes?

**Comment by fvictorio** [comment]
Yes, the animation is the only UI change, and I think it's just a (very-)nice-to-have for the time being.
