### ISSUE TITLE
Add "Share on Twitter" button

### ISSUE THREAD

**Issue by fvictorio** [protofire/gnosis-conditional-exchange#311]
We need to define which social networks are going to be supported, and where will the buttons be. I think we can start with just a Telegram button (wherever doesn't look too bad) and then work from that.

We can use [this library](https://www.npmjs.com/package/react-share) or something similar.

**Comment by mariano-aguero** [comment]
We need to decide, where to put the buttons? We need a design here, even if there is a library ?
Thoughts @gabitoesmiapodo @alongoni ?

**Comment by gabitoesmiapodo** [comment]
We need a design to know where to put the buttons.

**Comment by alongoni** [comment]
This is one option if we pretend to keep the social icons present in all steps/screens. Anyway if we preffeer to show share icons in a particular step/screen, we should think in others alternatives.

![14b - Conditional Exchange - Social Icons](https://user-images.githubusercontent.com/622217/72531127-9ca74080-384f-11ea-9759-b33ee4aab222.png)
@fvictorio @mariano-aguero @gabitoesmiapodo

**Comment by gabitoesmiapodo** [comment]
@fvictorio @mariano-aguero 

What would be we sharing, any section, or just a single market?

@alongoni 

I think placement is OK for desktop, but we should take into account responsive views too. The way it is now, it seems it will overlap with the main content when the screen is narrower.

If possible, we should use a placement which is compatible with desktop / tablet / mobile screen sizes.

**Comment by mariano-aguero** [comment]
> @fvictorio @mariano-aguero
> 
> What would be we sharing, any section, or just a single market?

We will share the market profile, so I think it  makes sense that  only exist in the market profile section
