### ISSUE TITLE
Prompt to share on Twitter after buying

### ISSUE THREAD

**Issue by fvictorio** [protofire/gnosis-conditional-exchange#322]
After the user buys some outcome token, it should somehow be prompted to tweet about her prediction. The tweet should be something like:

```
"<question>" I predicted <outcome>. What do you think? <url>
```

We might also include the amount somehow.

Not sure what is the best way to present this. A modal could work, but maybe is too annoying. @alongoni @gabitoesmiapodo what do you think?

**Comment by alongoni** [comment]
After buy shares, this modal can show a tweet like this.

![10d  - Conditional Exchange - Buy – twitter share](https://user-images.githubusercontent.com/622217/71924048-fb442e80-316c-11ea-9782-8a39a079c783.png)

@fvictorio

**Comment by gabitoesmiapodo** [comment]
Looks good.

@fvictorio  Semi related question: is it there something to inform the user that the transaction went successfully?

If not, we could use the same modal to give that info to the user.

**Comment by mariano-aguero** [comment]
@alongoni Can you add the zeplin design in the issue ? thanks

**Comment by gabitoesmiapodo** [comment]
https://zpl.io/bPnQndl

I'm still not sure this is 100% done.

I have an unanswered question above.

**Comment by fvictorio** [comment]
> @fvictorio Semi related question: is there something implemented to inform the user that the transaction went successfully?
>
> If not, we could use the same modal to give that info to the user.

@gabitoesmiapodo Yes, that's a good idea, @alongoni could you do that?

Also, the text might be a little different (for example, maybe we also include the amount of collateral spent), but I think that won't affect the design.

**Comment by alongoni** [comment]
![10d  - Conditional Exchange - Buy – twitter share](https://user-images.githubusercontent.com/622217/72261853-79cd2000-35f4-11ea-8aac-13454e4d3ffa.png)

**Comment by gabitoesmiapodo** [comment]
@alongoni 

Hm, I find the layout a little confusing. It's difficult for me to differentiate what's the message / twit, and what's information about the transaction. 

I mean: I first thought I was about to twit what's inside the gray block of text.

I think it would be better if you could improve the visual hierarchy in this design.

**Comment by alongoni** [comment]
I think between this two options:
a. Keep separate the modal for twitter and the alert box for systems messages.
![10d  - Conditional Exchange - Buy – twitter share](https://user-images.githubusercontent.com/622217/72280323-da6d5480-3616-11ea-842d-3554354ccc95.png)

b. All together in modal window, but using a subtitle for share on twitter
![10d  - Conditional Exchange - Buy – twitter share – 1](https://user-images.githubusercontent.com/622217/72280331-dc371800-3616-11ea-95ae-a509bf88706c.png)
@gabitoesmiapodo

**Comment by gabitoesmiapodo** [comment]
@alongoni 

First one is too contrived, I think.

This one looks good:

![10d  - Conditional Exchange - Buy – twitter share – 1](https://user-images.githubusercontent.com/622217/72280331-dc371800-3616-11ea-95ae-a509bf88706c.png)

Is still think that the Twitter part should be somehow less prominent. Also maybe we should allow the user to edit the tweet, or at least show it inside a `textarea`. What do you think @fvictorio ?

**Comment by fvictorio** [comment]
I _think_ when you share something in twitter, you are taken to Twitter with a pre-filled tweet ready to be sent. So, you can edit it later. If that's the case, I think there's no need for letting the user edit the message. @mariano-aguero can you check if this works like that?

> Is still think that the Twitter part should be somehow less prominent

I second this.

**Comment by mariano-aguero** [comment]
> I _think_ when you share something in twitter, you are taken to Twitter with a pre-filled tweet ready to be sent. So, you can edit it later. If that's the case, I think there's no need for letting the user edit the message. @mariano-aguero can you check if this works like that?
> 
> > Is still think that the Twitter part should be somehow less prominent
> 
> I second this.

Yes, works just like you said ...

![Screenshot_20200114_143421](https://user-images.githubusercontent.com/1144028/72367559-2bdf1780-36db-11ea-94a1-f57dacd00cc6.png)

**Comment by alongoni** [comment]
Maybe something like this? Any suggestion?
![10d  - Conditional Exchange - Buy – twitter share – 1](https://user-images.githubusercontent.com/622217/72453757-61990480-379e-11ea-8400-e5ffa063d6ee.png)

**Comment by gabitoesmiapodo** [comment]
@alongoni 

> Any suggestion?

Maybe make the "Your outcome..." text a little bigger, and the twit's text in a lighter color? I think it should be clear which part is information about the transaction, and which is a "Share this" part.

Also, it seems the textarea is not necessary. Besides that, I'm thinking we may not even need the message? Perhaps a "Share on Twitter" button or link, add Twitter's logo somewhere, and that could be the end of it.

I think something like that could be fine.

Not sure about the avatar, though. I don't know if we can fetch it from Twitter.

**Comment by alongoni** [comment]
The text info practically don't have changes, we can reuse the same info box in all app. 
![10d  - Conditional Exchange - Buy – twitter share – 1](https://user-images.githubusercontent.com/622217/72458181-e12ad180-37a6-11ea-8121-593b9e085ccb.png)
I'm ok using the  green "share" button, but anyway we can use this:
![image](https://user-images.githubusercontent.com/622217/72458593-a2e1e200-37a7-11ea-92a1-7e279f49fce6.png)

**Comment by gabitoesmiapodo** [comment]
@alongoni Yeah, use the blue button and we are good to go.

**Comment by alongoni** [comment]
@gabitoesmiapodo 
Less is more! :)
![10d  - Conditional Exchange - Buy – twitter share – 1](https://user-images.githubusercontent.com/622217/72460461-9d869680-37ab-11ea-87d5-87a64dab7e3c.png)

**Comment by gabitoesmiapodo** [comment]
@alongoni 

Perfect.

**Comment by mariano-aguero** [comment]
Added some logic on this branch `feature/add-twitter-share` . We can start from here, look like this ...
![Screenshot_20200116_181629](https://user-images.githubusercontent.com/1144028/72563721-072aa180-388d-11ea-923b-b0434f94a34a.png)
