### ISSUE TITLE
Change delete icon color

### ISSUE THREAD

**Issue by mariano-aguero** [protofire/gnosis-conditional-exchange#326]
Right now look like this ...

![Screenshot_20200103_142300.png](https://images.zenhubusercontent.com/5d70fed5c5574a4392cc4047/ad63d541-4064-41e1-8cb6-f35bf43fb590)

Looks like an error, so maybe is better to change the color to gray

**Comment by alongoni** [comment]
Maybe we can use this grey color (hex: #7F7F7F)
![03b - Conditional Exchange - Step 3 (Error)](https://user-images.githubusercontent.com/622217/71817558-f85e1680-3064-11ea-8c29-98d58dbd181f.png)
@mariano-aguero @fvictorio @gabitoesmiapodo

**Comment by gabitoesmiapodo** [comment]
@alongoni 

I'm actually OK with the current icon and your new suggestion, but maybe a trash can icon would be more obvious to the user?

**Comment by alongoni** [comment]
Thanks @gabitoesmiapodo!
I think current icon is more simple and consistency with other icons used in this dApp. But, anyway I can test trash icon. Some like this?. 
https://icons-for-free.com/iconfiles/png/512/delete+remove+trash+trash+bin+trash+can+icon-1320073117929397588.png

**Comment by gabitoesmiapodo** [comment]
@alongoni 

Yeah, it looks fine.

Give it a go, and let's see what the guys think.

**Comment by alongoni** [comment]
![03b - Conditional Exchange - Step 3 (Error) – 1](https://user-images.githubusercontent.com/622217/71821283-7bd13500-3070-11ea-9cbf-18da38d52fda.png)

**Comment by gabitoesmiapodo** [comment]
LGTM

**Comment by fvictorio** [comment]
Love it.

**Comment by mariano-aguero** [comment]
Looks great
