### ISSUE TITLE
Show proper colors in case of a tie

### ISSUE THREAD

**Issue by fvictorio** [protofire/gnosis-conditional-exchange#329]
If there are three or more outcomes, and there are two of them tied at the first place, we should show both with the winning color:

![image](https://user-images.githubusercontent.com/417134/71826936-edfc4680-307d-11ea-961d-670a23dbef83.png)

**Comment by mariano-aguero** [comment]
I think there are modifications in this PR https://github.com/protofire/gnosis-conditional-exchange/pull/339  that may affect this issue

**Comment by hpmaxi** [comment]
@mariano-aguero Yes, in the last version I see all outcomes with the same color (gray). This should be closed?
