### ISSUE TITLE
Add button to distribute all probabilities uniformly

### ISSUE THREAD

**Issue by fvictorio** [protofire/gnosis-conditional-exchange#336]
This needs a bit of design. We need a button when adding outcomes that just sets all probabilities to `100 / outcomesCount`.

(Actually, a better way to do this would be to keep track of it being used, and then use an empty distribution hint; then disable this when some probability is manually modified)

**Comment by mariano-aguero** [comment]
@alongoni Can you work on a design for this ? Thank you

**Comment by alongoni** [comment]
Add a checkbox "Distribute Unifomly".
![03b - Conditional Exchange - Step 3 (Distribute %)](https://user-images.githubusercontent.com/622217/72526267-c9098f80-3844-11ea-9871-08ea1cfcc389.png)
@fvictorio @gabitoesmiapodo

**Comment by alongoni** [comment]
May be in this way?. Below "100%" and checkbox on right side.
![03b - Conditional Exchange - Step 3 (Distribute %)](https://user-images.githubusercontent.com/622217/72617441-b7dd8300-3917-11ea-9496-7f7f0dc9adcd.png)
@gabitoesmiapodo

**Comment by gabitoesmiapodo** [comment]
Not entirely convinced, but it'll have to do.

**Comment by fvictorio** [comment]
What do you think about putting it below the "Add new outcome" component and left-aligned?

**Comment by gabitoesmiapodo** [comment]
@fvictorio We tried something like that. It would look even more visually disconnected.

I don't like it 100% aesthetically, but at least it's easily connected to the "Probabilities" column.

I think we might have to think about a different approach for this section. Maybe a dropdown or modal with some settings, I don't know yet.

**Comment by fvictorio** [comment]
Ok, let's just do it as that, at least to have the logic working.

@hpmaxi do you want to do this?
