### ISSUE TITLE
Use app through ENS in Rinkeby

### ISSUE THREAD

**Issue by mariano-aguero** [protofire/gnosis-conditional-exchange#347]

**Comment by mariano-aguero** [comment]
First of all, we need to register an ENS name. For this, just go to the ENS Manager (https://app.ens.domains/) to register a new name for the application, complete all the required step, set up the Public Resolver, and add the IPFS hash to your ENS record by choosing the `Content` record type.
Once set, it should show a link which points to ipfs gateway address (the link after content label).

![Screenshot_20200113_165046](https://user-images.githubusercontent.com/1144028/72287591-13f98c00-3626-11ea-950e-f0f3867c8f67.png)

Click the link and… tada! It shows the conditional exchange.
![Screenshot_20200113_160945](https://user-images.githubusercontent.com/1144028/72287605-1a880380-3626-11ea-8e9d-70f1c7c73d93.png)


If you open it via ENS contenthash supported browser/wallet (such as a browser with Metamask), you should be able to see the same content under the IPFS hash link.

If you put the ENS Domain, the trick is to add a slash at the end of the URL, like `example.eth/` and metamask will resolve the domain name.

**Comment by mariano-aguero** [comment]
@fvictorio are you OKEY with this ? Also we have this [blog](https://towardsdatascience.com/decentralizing-your-website-f5bca765f9ed) as a part of the investigation. The test domain is `http://omentest.eth/`

**Comment by fvictorio** [comment]
I think this is enough for now. I'm still curious about why EthDNS doesn't work with this, maybe it's just for mainnet? Anyway, let's just close this for the time being.
