### ISSUE TITLE
Improve note and add question button from realitio

### ISSUE THREAD

**Issue by mariano-aguero** [protofire/gnosis-conditional-exchange#368]
I think this can be improved a little
![Screenshot_20200117_135332.png](https://images.zenhubusercontent.com/5d70fed5c5574a4392cc4047/8d1948d8-c294-4187-a62d-d7ff16b3b8f2)

**Comment by alongoni** [comment]
Option 1: Add icons (ok and wrong) to the example and change redaction. Change: "Add question" to "Add realitio question"
![01b - Conditional Exchange - Step 1](https://user-images.githubusercontent.com/622217/72905901-08861f00-3d10-11ea-9fb7-3b3e5a730988.png)

Option 2: Improve the tooltip redaction and add a example question on placeholder.
![01c - Conditional Exchange - Step 1](https://user-images.githubusercontent.com/622217/72905910-0e7c0000-3d10-11ea-99a8-7b6778e37b1d.png)

@mariano-aguero @gabitoesmiapodo

**Comment by gabitoesmiapodo** [comment]
@alongoni 

Good, I like option 1.

**Comment by mariano-aguero** [comment]
Me too, I like option 1

**Comment by gabitoesmiapodo** [comment]
This is outdated and no longer a problem.
