### ISSUE TITLE
(Bug) Probabilities title looks bad

### ISSUE THREAD

**Issue by gabitoesmiapodo** [protofire/gnosis-conditional-exchange#374]
This should be fixed.

![Screen Shot 2020-01-21 at 14.44.16.png](https://images.zenhubusercontent.com/5dd4002e59c2320001aa6485/3d436936-9fc4-4970-9325-03500e664ddd)

**Comment by alongoni** [comment]
@gabitoesmiapodo I need more info about browser and version.

**Comment by gabitoesmiapodo** [comment]
@alongoni 

![Screen Shot 2020-01-21 at 15 06 18](https://user-images.githubusercontent.com/4015436/72830567-bdacce80-3c5f-11ea-84c1-632af8f0e7ab.png)

Any desktop resolution (1024x768 upwards), no zoom, I was working on `feature/add-twitter-share` when noticed, but `fix/Update-View-Market-Info-block-#300` or `master` are the same.

**Comment by mariano-aguero** [comment]
We need to test and close if the problem is already solved
