### ISSUE TITLE
Cannot enter to markets with zero funding

### ISSUE THREAD

**Issue by fvictorio** [protofire/gnosis-conditional-exchange#379]
Reproduction steps:

1. Create a new market
2. Remove all funding
3. Refresh I guess?

There's a "division by zero" error in the console so I guess the lack of funding is the problem.

**Comment by mariano-aguero** [comment]
Watch out this https://github.com/protofire/gnosis-conditional-exchange/pull/391/commits/e1f788cad08bc321ad75b92bb0f208191e9a700b
