### ISSUE TITLE
Market list - UI Redesign and feedback

### ISSUE THREAD

**Issue by leolower** [protofire/gnosis-conditional-exchange#404]

**Comment by alongoni** [comment]
Hi Stefan!
Market list: here we have the design based on @gabitoesmiapodo 's wireframes and the suggestions made.
![14 - Omen - Market List](https://user-images.githubusercontent.com/622217/73950313-7b7bc200-48da-11ea-8814-17b7916c6c2e.png)

Market List loading markets.
![14 - Omen - Market List – Load Searh](https://user-images.githubusercontent.com/622217/73950318-7cacef00-48da-11ea-9684-eaa2d2f6c639.png)

**Comment by Georgi87** [comment]
I like them! A few suggestions: The search filters/bar take too much of the vertical space. Could we make them more compact together?

Regarding the navbar: Could we evaluate something similar to https://uniswap.exchange/? Transparent background and only the logo and buttons? I think we decided to go with a modal for help so there might be no need for a dedicated help button. I would also not mention mainnet next to the user's address.

**Comment by alongoni** [comment]
Thanks! This is an alternative, place the filters on the same line.
![14 - Omen - Market List - filters one line](https://user-images.githubusercontent.com/622217/73952942-69038780-48de-11ea-8acd-fe084aca9024.png)

**Comment by leolower** [comment]
Closing because the dxDAO provided the UI Design.
