### ISSUE TITLE
Merge outcomes to get collateral when removing funding

### ISSUE THREAD

**Issue by leolower** [protofire/gnosis-conditional-exchange#417]
When someone removes funding, they get two things:

- Some part of the fee as collateral
- Some part of the pooled outcome tokens

The outcome tokens should be merged as much as possible to convert them back to collateral. The user then would receive `collateralFee + min(outcomes)` in collateral and `outcomes.map(outcome - min(outcomes)` as outcomes.

Since we are using the CPK, all of this can be batched. The transactions sent by the CPK are:

- Proxy calls the funding removal method in the Market contract
- Proxy merges `min(outcomes)` outcome tokens
- Proxy sends all the collateral back to user

Notice that there might be some outcomes left in the proxy. That's ok because we never send the outcome tokens back to the user.

The only case when there are no leftover outcome tokens is when the odds for all the outcomes are the same.

**Comment by fvictorio** [comment]
Sorry, I shouldn't have closed this, my bad.
