### ISSUE TITLE
Coronavirus Omen fork

### ISSUE THREAD

**Issue by leolower** [protofire/gnosis-conditional-exchange#471]
- [x] Show only questions created by the admin account
- [x] Hide create button
- [x] Use custom account as Realitio arbitrator
- [x] Allow only USDC
- [x] Replace 3box with disqus
- [x] Allow setting featured comments in disqus
- [x] Set fee at 0%
- [x] Hide filters
- [x] New adaptor contract (wait for Alan to deploy it)
- [x] Partial payouts. Sync with Edmund from realit.io
- [x] Exclude people from the US. Try to do it on the UI. Sync with Sight team.
- [x] Hide Pool liquidity / Fund screens
- [x] Bring all corona changes to this repo
- [x] Market creation: create nuanced binary markets (double-check deployed version)
- [x] Hardcoded numbers and placeholders: make them work or remove them
- [x] Hide categories filter on the market list
- [x] All P1 items from this list: https://docs.google.com/spreadsheets/d/1QPVkONyJd-cugY38LJZbIpBIR42rRMlwQbKMU38P_GQ/edit#gid=0
- [x] Replace categories with CV specific ones. Make them say "Coronavirus-*" on realit.io
- [x] Add new FAQ page (wait for Stefan to provide the text or file)
- [x] Add Terms and Conditions checkbox next to the  connect button with link to T&C

**Comment by fvictorio** [comment]
0% fee can be set via the env variable. I only had to remove a validation in the create form.
