### ISSUE TITLE
UI Polishment

### ISSUE THREAD

**Issue by pimato** [protofire/gnosis-conditional-exchange#477]
Omen Logo should have include a hover, please check the design specification here:
[Playground](https://www.figma.com/proto/fDKaHCCfwqmOmOBg5xkSoo/Pages?node-id=1497%3A25189&viewport=50%2C179%2C0.1301533579826355&scaling=min-zoom)
[Design Specification](https://www.figma.com/file/fDKaHCCfwqmOmOBg5xkSoo/Pages?node-id=1497%3A25189)
Once the user clicks on Omen he should get redirected to the main Omen page

**Comment by pimato** [comment]
all label buttons should have: 

![Screenshot 2020-03-20 at 16.35.52.png](https://images.zenhubusercontent.com/5e3c1bff9b671a32e8bb6f35/43303689-8c8a-442a-851d-4786027a515e)

padding-left: 10px
padding-right: 10px
margin-right: 10px

**Comment by pimato** [comment]
All Dropdown should have the same hover design as the main button:

![Screenshot 2020-03-20 at 16.38.32.png](https://images.zenhubusercontent.com/5e3c1bff9b671a32e8bb6f35/aef81f35-fa2c-4fe6-95b0-34baced6a45b)

**Comment by pimato** [comment]
One of the connection flow state is missing in the UI. If a new users clicks on Metamask for the first time Metamask requires an approval from the user. The UI should tell the user that an action from the user is required on the Metamask extension. We do that by showing this:

![Screenshot 2020-03-20 at 16.50.04.png](https://images.zenhubusercontent.com/5e3c1bff9b671a32e8bb6f35/7f4dc668-fa8b-4d21-b6f5-25ed263d3155)

Please check out the UI/UX flow in the [Playground](https://www.figma.com/proto/fDKaHCCfwqmOmOBg5xkSoo/Pages?node-id=864%3A1&viewport=45%2C348%2C0.13349056243896484&scaling=min-zoom)

The design specification for the metamask approval request modal state can be looked up here:
https://www.figma.com/file/XQUrkaj1A0KIofHjgiLP91/Widgets?node-id=240%3A3529

**Comment by pimato** [comment]
Is it possible to have the Sort by button in the design like this ?

![Screenshot 2020-03-20 at 16.53.17.png](https://images.zenhubusercontent.com/5e3c1bff9b671a32e8bb6f35/21c70d62-84ec-4d52-87d8-f4f6207b0231)

**Comment by gabitoesmiapodo** [comment]
All of these issues except for the last two should be addressed on https://github.com/protofire/gnosis-conditional-exchange/pull/495

I've created two separated issues for the remaining problems, as they could take a little bit more time to fix:

- https://github.com/protofire/gnosis-conditional-exchange/issues/494
- https://github.com/protofire/gnosis-conditional-exchange/issues/493
