### ISSUE TITLE
add Market State UI for binary market/nounced binary market with winning/loosing/invalid state

### ISSUE THREAD

**Issue by pimato** [protofire/gnosis-conditional-exchange#481]
Hey guys,

we need to have a UI which indicates the user the final states of an market. 

[Playground for all states
](https://www.figma.com/proto/fDKaHCCfwqmOmOBg5xkSoo/Pages?node-id=1524%3A586&viewport=121%2C90%2C0.1316000074148178&scaling=min-zoom)

### Binary Market closed and user won
![winning-redeem.png](https://images.zenhubusercontent.com/5e3c1bff9b671a32e8bb6f35/f62ae3be-d70c-4078-9be7-fdab4361ebd2)
[Design specification on Figma](https://www.figma.com/file/fDKaHCCfwqmOmOBg5xkSoo/Pages?node-id=1524%3A874)

### Binary Market closed and user lost
![closed-lost.png](https://images.zenhubusercontent.com/5e3c1bff9b671a32e8bb6f35/4441e09e-ad2c-48e7-83d4-bc0673f08a57)
[Design specification on Figma](https://www.figma.com/file/fDKaHCCfwqmOmOBg5xkSoo/Pages?node-id=1556%3A1728)

### Binary Market invalid
![market-invalid.png](https://images.zenhubusercontent.com/5e3c1bff9b671a32e8bb6f35/07b45056-16ff-4437-a985-378cbb0057e1)
[Design specification on Figma](https://www.figma.com/file/fDKaHCCfwqmOmOBg5xkSoo/Pages?node-id=1569%3A0)

### Nounced Binary Market two outcomes
![binary.png](https://images.zenhubusercontent.com/5e3c1bff9b671a32e8bb6f35/0f13edb4-7535-47d0-82b4-5961759c80dd)

[Design specification on Figma](https://www.figma.com/file/fDKaHCCfwqmOmOBg5xkSoo/Pages?node-id=1571%3A0)

**Comment by gabitoesmiapodo** [comment]
@fvictorio @hpmaxi 

I think we already have this in place, please have a look and let me know if there are some components (or logic) missing.
