### ISSUE TITLE
"Has winning outcomes" filter doesn't handle nuanced binaries nor undefined answers

### ISSUE THREAD

**Issue by fvictorio** [protofire/gnosis-conditional-exchange#508]
Not important for the corona markets version, but: the filter to show only markets where you have winning outcomes is using the old method for getting the winner outcome. Meaning this doesn't handle scenarios where there are multiple outcomes with payouts (nuanced binaries and undefined answers).

**Comment by leolower** [comment]
This filter does not exist anymore.
