### ISSUE TITLE
can`t withdraw my shares on an resolved/closed market

### ISSUE THREAD

**Issue by pimato** [protofire/gnosis-conditional-exchange#524]
Hey guys, 

I am trying to withdraw my shares and it seems like the button to redeem is not appearing:

<img width="639" alt="Screenshot 2020-04-12 at 20 32 10" src="https://user-images.githubusercontent.com/5337809/79076727-b47e4b80-7cfc-11ea-9235-d18a18c81472.png">

checking on realit.io:
<img width="828" alt="Screenshot 2020-04-12 at 20 28 25" src="https://user-images.githubusercontent.com/5337809/79076732-bea04a00-7cfc-11ea-9c38-507eb606221f.png">

it is definitely resolved.

**Comment by fvictorio** [comment]
@pimato can you check if this is still happening?

**Comment by fvictorio** [comment]
Closing this since I've tested the redeem feature a lot and still hasn't happened. Please re-open if it happens again.
