### ISSUE TITLE
Footer should always be visible.

### ISSUE THREAD

**Issue by auryn-macmillan** [protofire/gnosis-conditional-exchange#575]
The footer, with disclaimer text and links to the Terms and Conditions, etc, should always be visible on the page.
Can we make its position absolute?

**Comment by auryn-macmillan** [comment]
Actually, thinking about it. It would be really nice if the content of the list scrolled, while everything else stayed in a fixed position; including the title and categories. The only thing on the "markets" page (`/#/`) that needs to scroll is the list of markets.

**Comment by fvictorio** [comment]
The first part of this issue is fixed (not deployed yet). About scrolling only the list: I think this would need some design changes. Could you open a new issue for that so we can track it separately?
