### ISSUE TITLE
Usability issue on market list and buy outcome

### ISSUE THREAD

**Issue by leolower** [protofire/gnosis-conditional-exchange#577]
I made some light user testing and recorded this: https://nimb.ws/lVjrJo

There are 2 issues:
- On the market list you can see "33.00% <300.000" which reads as "33% is less than 300k" and confused the user. I explained these are 2 separate things but he couldn't figure it out until he opened the market details.
- Once on the buy page, he again tried to click on any part of the outcome in order to select it. Later he tried the radio button on the left.

**Comment by leolower** [comment]
@pimato what do you think?

**Comment by gabitoesmiapodo** [comment]
> The "buy" button is not very visible and clicking on the outcome is more natural. 

Removing the footer (or making it not fixed) should improve this. Otherwise, we maybe  should think about making some changes to the design (ie: maybe placing the buttons at the top?)

**Comment by gabitoesmiapodo** [comment]
> Once on the buy page, he again tried to click on any part of the outcome in order to select it.

Yeah, this should be an easy fix.

**Comment by gabitoesmiapodo** [comment]
> On the market list you can see "33.00% <300.000" which reads as "33% is less than 300k" and confused the user. 

I don't understand what this means either.
