### ISSUE TITLE
Markets are displayed multiple times

### ISSUE THREAD

**Issue by clesaege** [protofire/gnosis-conditional-exchange#616]
In the main page, a market is sometimes displayed multiple times (2 or even sometimes 3 times).
![bug](https://user-images.githubusercontent.com/8873352/80294212-de088f80-875e-11ea-8b3d-c59781c03aec.png)

**Comment by leolower** [comment]
@clesaege could you provide the steps to reproduce this issue? We couldn't find any way to reproduce it here.

**Comment by fvictorio** [comment]
Closing this, please re-open if it happens again.
