### ISSUE TITLE
Review Omen Arbitrator contract

### ISSUE THREAD

**Issue by Georgi87** [protofire/gnosis-conditional-exchange#618]
https://github.com/nicoelzer/Omen-Arbitrator

**Comment by leolower** [comment]
Review the code, tell if this can be used for Omen.

**Comment by fvictorio** [comment]
I just skimmed it, but looks like it can be used. Only thing I noticed is that it doesn't have a `withdraw` function for collecting the arbitration fees. Let me know if a more in-depth review of the code is needed.

**Comment by nicoelzer** [comment]
Hey @leolower @fvictorio,

thanks for taking the time to review the contract.

- @fvictorio the function requestArbitration() will redirect the collected fees to the defined address (feeRecipient)

- Took the chance and updated to Solidity 0.6.2

**Comment by fvictorio** [comment]
@nicoelzer Makes sense, thanks! One small thing I forgot to mention: I think the `Withdraw` event is being emitted twice when `requestArbitration` is called.

@Georgi87 I think this can be used in Omen.

**Comment by nicoelzer** [comment]
> @nicoelzer Makes sense, thanks! One small thing I forgot to mention: I think the Withdraw event is being emitted twice when requestArbitration is called.

@fvictorio indeed, thanks for pointing out. Just removed the duplicate.

**Comment by fvictorio** [comment]
Closing this for triage purposes. Please re-open if there's anything else needed here.
