### ISSUE TITLE
Graph showing the history of Odds over time

### ISSUE THREAD

**Issue by leolower** [protofire/gnosis-conditional-exchange#623]
A graph showing the odds over time

**Comment by leolower** [comment]
- Thomas is working on mockups. 
- The current graph can provide this data but we should confirm.

**Comment by fvictorio** [comment]
I think that a chart like that will need to be done ad hoc, which will take a lot more time. A quicker alternative is to use an existing charting library. For example, I think [this chart](https://recharts.org/en-US/examples/PercentAreaChart) would look good for Omen.

For the implementation, some notes.

First, I would start with a hardcoded time span, for example last week. Adding controls like "7d", "1M', "YTD", etc. could be done in a separate iteration.

Then we'd need to take that span of time and generate a list of block numbers evenly spaced for that period. Then we can query the graph for each block number and get the corresponding values.

**Comment by pimato** [comment]
I think those are great suggestions. I am gonna have new designs for the graph which should fit very well starting next week. So we should move forward with the implementation of it also with those time pickers.

**Comment by fvictorio** [comment]
Cool. I'll start working on the core logic, that should be independent of how the chart ends up looking.

**Comment by pimato** [comment]
@hpmaxi @fvictorio @leolower I am done with styling the new chart. I´ve also included a way to show the picker for the time period. Check it out:

[Playground](https://www.figma.com/proto/GNoehJ64fqfptghsjYqvTJ/Playground-V2?node-id=2291%3A13&viewport=295%2C778%2C0.3912472128868103&scaling=min-zoom)
[Design specification](https://www.figma.com/file/8ewqNUtmCOryLQDZiP6Rfc/V1?node-id=211%3A17297)

**Comment by gabitoesmiapodo** [comment]
Made some changes to the styling.

It was looking like these:

![Screen Shot 2020-05-13 at 16 50 53](https://user-images.githubusercontent.com/4015436/81866945-584e5780-9546-11ea-9b28-336eb8346f1b.png)
![Screen Shot 2020-05-13 at 16 51 04](https://user-images.githubusercontent.com/4015436/81866957-5ab0b180-9546-11ea-8ac3-6ab54ec31bee.png)
![Screen Shot 2020-05-13 at 16 51 12](https://user-images.githubusercontent.com/4015436/81866961-5be1de80-9546-11ea-84f4-1007f406780e.png)
![Screen Shot 2020-05-13 at 16 52 44](https://user-images.githubusercontent.com/4015436/81866966-5c7a7500-9546-11ea-9cb0-19ca748ad21d.png)

Should look like these now:

![Screen Shot 2020-05-13 at 18 18 11](https://user-images.githubusercontent.com/4015436/81867011-6bf9be00-9546-11ea-94d0-478373fe4059.png)
![Screen Shot 2020-05-13 at 18 17 58](https://user-images.githubusercontent.com/4015436/81867015-6dc38180-9546-11ea-8785-0b9477abf605.png)
![Screen Shot 2020-05-13 at 18 18 16](https://user-images.githubusercontent.com/4015436/81867016-6ef4ae80-9546-11ea-9dce-29c6cc12f048.png)
