### ISSUE TITLE
Cannot sell small amount of shares

### ISSUE THREAD

**Issue by Georgi87** [protofire/gnosis-conditional-exchange#627]
![Bildschirmfoto 2020-04-30 um 14 35 43](https://user-images.githubusercontent.com/259400/80711039-03472600-8af0-11ea-8dc2-11ce5457eed1.png)

**Comment by leolower** [comment]
@Georgi87 this seems to be an old version. The most up to date UI has link to use the actual value when clicking on the label. We need to deploy to production and re-test this.

**Comment by fvictorio** [comment]
This seems to work fine now. Please re-open if that's not the case.
