### ISSUE TITLE
Review conditional tokens subgraph to determine if we can draw a probability chart over time

### ISSUE THREAD

**Issue by leolower** [protofire/gnosis-conditional-exchange#637]

**Comment by fvictorio** [comment]
See https://thegraph.com/docs/graphql-api#time-travel-queries

I think the complexity here lays in how to define the blocks that will be queried. I can think of two approaches:

1. Get the block at which the market maker was deployed, and divide the interval in N parts. Query each block, plot that.
2. Make a temporary chart, irrespective of when the market was created (for example, last month). This can be iterated over and add other time spans.

I think 2 is a better option. It's more consistent with how these charts are usually done, and involves less wizardry for getting the initial block.

I guess the design will also influence this decision.
