### ISSUE TITLE
Impossible to add more than 4 outcomes

### ISSUE THREAD

**Issue by clesaege** [protofire/gnosis-conditional-exchange#648]
The UI does not allow to add more than 4 outcomes. The "Add new outcome" fields becomes greyed out an unfillable after 4 outcomes are added.
![image](https://user-images.githubusercontent.com/8873352/81322563-19bf2580-908c-11ea-9e60-5138230b13eb.png)

**Comment by leolower** [comment]
This is configurable and can be changed at build time. There is a hard limit that the smart contract will allow though. We have tested with up to 10 outcomes.
