### ISSUE TITLE
Loading of Chart requires an indicator

### ISSUE THREAD

**Issue by pimato** [protofire/gnosis-conditional-exchange#663]
Hey, I just played around with  https://deploy-preview-657--conditional.netlify.app/ and it seems like the loading of the chart requires a little bit of time. To not have the user feel like it is lagging we should include a loading indicator.

[Playground](https://www.figma.com/proto/GNoehJ64fqfptghsjYqvTJ/Playground-V2?node-id=2291%3A1&viewport=252%2C517%2C0.21183109283447266&scaling=min-zoom)
[Design Specification](https://www.figma.com/file/GNoehJ64fqfptghsjYqvTJ/Playground-V2?node-id=2291%3A1)

**Comment by gabitoesmiapodo** [comment]
This should be addressed on https://github.com/protofire/gnosis-conditional-exchange/issues/623 now.
