### ISSUE TITLE
After Market Import/add Question all inputfield buttons should have a coherent the "filled-disable" style

### ISSUE THREAD

**Issue by pimato** [protofire/gnosis-conditional-exchange#669]
Currently:
<img width="602" alt="Screenshot 2020-05-13 at 20 46 16" src="https://user-images.githubusercontent.com/5337809/81852117-d1f04080-955a-11ea-8412-48ba78749685.png">
Should:
<img width="686" alt="Screenshot 2020-05-15 at 10 43 18" src="https://user-images.githubusercontent.com/5337809/82030568-e76b8480-9698-11ea-8e22-b8d495bf20df.png">

Check out the design specification here:
https://www.figma.com/file/8ewqNUtmCOryLQDZiP6Rfc/V1?node-id=211%3A20358

**Comment by gabitoesmiapodo** [comment]
@pimato could you check the images? Both look the same to me.

**Comment by pimato** [comment]
@gabitoesmiapodo screenshot fixed!
