### ISSUE TITLE
After clearing question, answers should be removed

### ISSUE THREAD

**Issue by pimato** [protofire/gnosis-conditional-exchange#670]
After clicking on clear question, everything should go to idle mode
<img width="604" alt="Screenshot 2020-05-13 at 20 53 23" src="https://user-images.githubusercontent.com/5337809/81852773-d8cb8300-955b-11ea-9066-f1063813cbd2.png">

**Comment by fvictorio** [comment]
What do you mean by "Clicking on clear question"?

**Comment by pimato** [comment]
@fvictorio at the top right corner of the widget:
<img width="601" alt="Screenshot 2020-05-15 at 10 41 09" src="https://user-images.githubusercontent.com/5337809/82030340-9d829e80-9698-11ea-9c9f-3346da2982fe.png">
