### ISSUE TITLE
Inputfield error doesn`t make any sense

### ISSUE THREAD

**Issue by pimato** [protofire/gnosis-conditional-exchange#673]
this message appears when I am trying to put any number into the inputfield:

<img width="602" alt="Screenshot 2020-05-13 at 21 15 02" src="https://user-images.githubusercontent.com/5337809/81855096-209fd980-955f-11ea-86fe-370076ac9d82.png">

If the error wants to imply that the user has no funds we should say **Insufficient balance**

**Comment by gabitoesmiapodo** [comment]
I guess that's because your wallet has no funds (you can't input a value greater that your wallet's balance). 

Maybe the text field should be disabled when balance == 0?

**Comment by pimato** [comment]
> I guess that's because your wallet has no funds (you can't input a value greater that your wallet's balance).
> 
> Maybe the text field should be disabled when balance == 0?

Yeah, maybe I would be for just telling the user that he/she has no funds by saying "**Insufficient balance**". Currently the message says that the user must have less or 0 balance, which is totally wrong.

I am against disabling the inputfield as we want to give the user the chance to play around with the funding action. Users may want to know how much pool tokens they get if funded amount X.
