### ISSUE TITLE
Add Omen footer with version and contract hyperlink similar to Mesa

### ISSUE THREAD

**Issue by pimato** [protofire/gnosis-conditional-exchange#685]
It is important in terms of security to have links to the codebase and the contracts like we have at Mesa:

<img width="298" alt="Screenshot 2020-05-15 at 15 38 34" src="https://user-images.githubusercontent.com/5337809/82056488-53aeae00-96c2-11ea-999a-f985a2ae5958.png">

**Comment by gabitoesmiapodo** [comment]
@pimato could you provide a simple design showing where you'd prefer to have that information shown?

**Comment by pimato** [comment]
sorry @gabitoesmiapodo my fault, it is very similar to the footer of the corona markets:
<img width="512" alt="Screenshot 2020-05-21 at 21 31 16" src="https://user-images.githubusercontent.com/5337809/82598120-6a657100-9baa-11ea-89de-ee82daec81fc.png">

https://www.figma.com/file/GNoehJ64fqfptghsjYqvTJ/Playground-V2?node-id=1933%3A231

**Comment by fvictorio** [comment]
> **Omen Contract** should hyperlink to etherscan main omen contracts

Which one should we use? ConditionalTokens or the MarketMakerFactory? Or the deployed contract for the current market (this would only work for market details, not for the home page).

**Comment by pimato** [comment]
I would say lets go with the MarketMakerFactory for now!
