### ISSUE TITLE
How to add Binary Markets?

### ISSUE THREAD

**Issue by nicoelzer** [protofire/gnosis-conditional-exchange#694]
Users currently can select Binary in the Question Type Filter. How to actually create a binary market?

<img width="582" alt="Binary" src="https://user-images.githubusercontent.com/1383195/82174472-208e3980-98d1-11ea-925e-3131b4a612d7.png">

**Comment by fvictorio** [comment]
The create component only supports categorical markets right now. Even if only two outcomes are used, the question is a categorical one with two outcomes.

**Comment by nicoelzer** [comment]
@fvictorio thanks for clarifying. What would it take to also create Binary Markets?

**Comment by fvictorio** [comment]
- Design for changing the kind of market (for example a checkbox or a dropdown for selecting the kind of market).
- Design for how the outcome input will look. At the very least, it should show hardcoded the No/Yes outcomes and then you can edit only the odds. An improvement over that is to just change one and adjust the other automatically (which we've done in a previous iteration).
- All the changes to the underlying logic. I don't think there will be a lot of changes, but some adaptation will surely be necessary.
