### ISSUE TITLE
Remove time from Earliest Resolution Date

### ISSUE THREAD

**Issue by pimato** [protofire/gnosis-conditional-exchange#698]
<img width="303" alt="Screenshot 2020-05-19 at 10 56 27" src="https://user-images.githubusercontent.com/5337809/82306682-a688ae00-99bf-11ea-8584-7d7cdba56f3e.png">

It is sufficient to show only the date. This will also fix the broken padding.

**Comment by clesaege** [comment]
Actually the exact date is important in order to spot invalid markets (markets whose result would not be known by the resolution date).

**Comment by pimato** [comment]
> Actually the exact date is important in order to spot invalid markets (markets whose result would not be known by the resolution date).

I am not requesting to remove the resolution date completely but remove the **time**. We can add a hover if users request it

**Comment by clesaege** [comment]
Here the time has been completely removed, so we're probably have people trying to scam by creating intentionally invalid markets whose resolution date is just a few hours before the info is to be known.

**Comment by fvictorio** [comment]
@clesaege I might be missing something here, but I don't think this is a big issue.

The market maker continues working (at the contract level) after the question is resolved. So the liquidity providers already have the responsibility to withdraw their liquidity before the event happens. If they do that, and they are very incentivized to do it, then the issue of the specific time doesn't matter that much. What do you think?

**Comment by clesaege** [comment]
Actually it's a very big issue and was the most common attack against Augur markets.
The resolution date is the resolution time of the realitio question too.
If the question can't be answered by the resolution time, people should report the question as invalid.
Let's imagine that we have a market on a football match the 1st of January.
The football match should finish at 16:00 now look at those 2 markets:
- Market A has for resolution time January 1st 17:00 UTC.
- Market B has for resolution time January 1st 15:00 UTC.
At the time market A question opens, the result is know, so market A resolves correctly.
But at the resolution time of market B, the result is not known yet, so the market will resolve as invalid.
But in the new interface, both are displayed the same.

**Comment by gabitoesmiapodo** [comment]
We could add a tooltip, or ask @pimato if he can tweak the design a little.

**Comment by fvictorio** [comment]
> At the time market A question opens, the result is know, so market A resolves correctly.
> But at the resolution time of market B, the result is not known yet, so the market will resolve as invalid.

Would this be mitigated if we assume that the timeout in Realitio is always 1 day?

I see your point here, I just don't think that there's a huge difference between showing it and not showing it, as long as there's a link to Realitio or a tooltip. I mean, given what you're saying I would err on the safe side and display the time as it was before, but I don't see it as a big isssue if we don't—again provided there's enough timeout in Realitio and that there's an easy way to obtain the full datetime. YMMV.
