### ISSUE TITLE
Chart missing divider

### ISSUE THREAD

**Issue by pimato** [protofire/gnosis-conditional-exchange#699]
Hey,

currently the header title of the chart has no border bottom:
<img width="619" alt="Screenshot 2020-05-19 at 11 00 28" src="https://user-images.githubusercontent.com/5337809/82306955-04b59100-99c0-11ea-96c0-417fd4f8370a.png">

should:
<img width="897" alt="Screenshot 2020-05-19 at 11 01 55" src="https://user-images.githubusercontent.com/5337809/82307086-2c0c5e00-99c0-11ea-9857-bdef39691b6b.png">

**Comment by gabitoesmiapodo** [comment]
Blocked until https://github.com/protofire/gnosis-conditional-exchange/pull/708 is solved.
