### ISSUE TITLE
1 Week Chart X-Scale renaming

### ISSUE THREAD

**Issue by pimato** [protofire/gnosis-conditional-exchange#701]
Currently:
<img width="605" alt="Screenshot 2020-05-19 at 11 06 45" src="https://user-images.githubusercontent.com/5337809/82307642-ed2ad800-99c0-11ea-8276-705250aed2d5.png">

Should:
<img width="824" alt="Screenshot 2020-05-19 at 11 07 54" src="https://user-images.githubusercontent.com/5337809/82307696-016ed500-99c1-11ea-9642-b6f4f55529b2.png">

**Comment by fvictorio** [comment]
Not sure I get this. The way I understand it, 1W shows the last week, so this seems fine?

**Comment by pimato** [comment]
> Not sure I get this. The way I understand it, 1W shows the last week, so this seems fine?

Yeah I think the title was wrong, sorry.
The year here is not necessary and can we just change it to the way I show it in **should**?

**Comment by fvictorio** [comment]
Ohhhh, got it :+1:
