### ISSUE TITLE
Trade history doesn't work

### ISSUE THREAD

**Issue by clesaege** [protofire/gnosis-conditional-exchange#703]
![bug](https://user-images.githubusercontent.com/8873352/82373153-0cebeb80-9a15-11ea-99a9-4a8fa61bd29e.png)

**Comment by fvictorio** [comment]
This seems to be a very recent change from thegraph that doesn't allow fetching data from different blocks in the same query. We'll need to fetch the data some other way, I don't know how.

**Comment by fvictorio** [comment]
For the record, this commit broke the chart: https://github.com/graphprotocol/graph-node/commit/08582b45a0cec7a34a9ca19a8b4826333d7d2b84 Working on changing the approach now.
