### ISSUE TITLE
Show only 4 markets, if user wants to see more he/she can click on "Load more"

### ISSUE THREAD

**Issue by pimato** [protofire/gnosis-conditional-exchange#719]
Hey,

currently all open markets are shown, which is way too much information at once. We should limit it to 4 markets and if the user wants he can load more which will load 4 more markets.

Currently:
<img width="670" alt="Screenshot 2020-05-21 at 21 44 24" src="https://user-images.githubusercontent.com/5337809/82599265-4145e000-9bac-11ea-85ba-6de60eeb91ea.png">

Should:
<img width="616" alt="Screenshot 2020-05-21 at 21 43 38" src="https://user-images.githubusercontent.com/5337809/82599200-2bd0b600-9bac-11ea-8e24-9325bfbb442a.png">

**Comment by gabitoesmiapodo** [comment]
Currently pagination == 10, and the "Load more" loads more items when the user gets to it by scrolling.

I'm guessing that if the screen is big enough, the "Load more" button triggers and loads the next batch of 10 items, until it is out of view.

It'll probably do the same with 4 items, so the fix probably will need a little more work than changing the pagination number.

**Comment by gabitoesmiapodo** [comment]
I actually tried with 4 items, and yes: it immediately loads 4 more items, and then another 4 more until it's out of view.

**Comment by pimato** [comment]
yeah, I am not sure why the scrolling triggers more list items. The goal with reducing the item list is in general to not overwhelm the user. We additionally overwhelm him by auto load more text into the screen.

**Comment by fvictorio** [comment]
I think it's just removing the `react-waypoint` functionality that trigger the loading when the bottom of the screen is reached.

**Comment by gabitoesmiapodo** [comment]
Yeah, we could just disable / remove it.
