### ISSUE TITLE
Add instructions to readme for not only build but simply run the omen version

### ISSUE THREAD

**Issue by pimato** [protofire/gnosis-conditional-exchange#721]
Hey guys,

I am currently trying to get omen running and it seems like there are some issues:

changed:
```
REACT_APP_VERSION=omen
REACT_APP_INFURA_PROJECT_ID="5dab3f3dxxxx77cf9f34dd"
```

and I am getting:
<img width="1032" alt="Screenshot 2020-05-21 at 22 40 55" src="https://user-images.githubusercontent.com/5337809/82604163-27100000-9bb4-11ea-95c0-9f6f5a261a73.png">

maybe add an env. example file for omen which works?

**Comment by hpmaxi** [comment]
@pimato 
Does it work If you change it again to corona?
Do you made those changes to a file named `.env`?

**Comment by pimato** [comment]
Hey sorry guys, this was a mistake on my part.
