### ISSUE TITLE
Remove duplicate "You own x.xx Shares" from outcome row item

### ISSUE THREAD

**Issue by pimato** [protofire/gnosis-conditional-exchange#737]
Now that we have a specific column for the users outcome token shares we should remove the **You own 17.65 Shares** below the outcome description:

<img width="613" alt="Screenshot 2020-05-27 at 12 58 13" src="https://user-images.githubusercontent.com/5337809/83011296-ec75ef80-a019-11ea-9d62-97dd4d5f227e.png">

<img width="604" alt="Screenshot 2020-05-27 at 12 58 18" src="https://user-images.githubusercontent.com/5337809/83011304-eed84980-a019-11ea-901d-ad462415aeb9.png">

example result:
<img width="603" alt="Screenshot 2020-05-27 at 13 00 49" src="https://user-images.githubusercontent.com/5337809/83011425-20e9ab80-a01a-11ea-9178-575832f884dd.png">

**Comment by KadenZipfel** [comment]
https://github.com/protofire/gnosis-conditional-exchange/pull/759
