### ISSUE TITLE
Integrate DxDAO's TCR for collateral tokens

### ISSUE THREAD

**Issue by leolower** [protofire/gnosis-conditional-exchange#739]

**Comment by leolower** [comment]
@pimato please share the rinkeby address and specs when you have them.

**Comment by pimato** [comment]
contract on main network:
https://etherscan.io/address/0x93db90445b76329e9ed96ecd74e76d8fbf2590d8#code

contract on rinkeby network:
https://rinkeby.etherscan.io/address/0x03165df66d9448e45c2f5137486af3e7e752a352

here is the class from mesa codebase:
https://github.com/gnosis/dex-js/blob/master/src/contracts/gen/Tcr.d.ts

**Comment by pimato** [comment]
the creation of the omen list is currently pending:
http://alchemy.daostack.io/dao/0x519b70055af55a007110b4ff99b0ea33071c720a/proposal/0x544220cb5686527f88fe5950417b4c10dc212a636dae871087720e7d5a415341
