### ISSUE TITLE
REACT_APP_VERSION=omen request terms and conditions approval

### ISSUE THREAD

**Issue by pimato** [protofire/gnosis-conditional-exchange#741]
if ```REACT_APP_VERSION=omen``` is set, we should make sure to actually show everything related to Omen and not Coronainformationmarkets. Same applies to the footer!

<img width="374" alt="Screenshot 2020-05-29 at 19 20 37" src="https://user-images.githubusercontent.com/5337809/83287183-7e7c2480-a1e1-11ea-95a2-b95526448174.png">

**Comment by KadenZipfel** [comment]
https://github.com/protofire/gnosis-conditional-exchange/pull/761
