### ISSUE TITLE
Page title gets set as 'Corona Information Markets' on Omen

### ISSUE THREAD

**Issue by KadenZipfel** [protofire/gnosis-conditional-exchange#760]
AFAIK, the page title should be set as 'Omen' if REACT_APP_VERSION=omen. Instead, after load the page title is set to 'Corona Information Markets'

**Comment by nicoelzer** [comment]
@KadenZipfel also noticed this one- The Metadata is pulled from the .env – changing the REACT_APP_TITLE worked for me

**Comment by gabitoesmiapodo** [comment]
Yeah, `REACT_APP_TITLE` must be used to set the title.
