### ISSUE TITLE
Fee set in the ENV file is not used everywhere 

### ISSUE THREAD

**Issue by leolower** [protofire/gnosis-conditional-exchange#779]
seems like the market fee in the env file defines only one side of the market: keybase://chat/dx_dao#Omen/1442
at least the frontend is showing Trading fee earnings of 4%
if the market fee is set with 2% in the env file

**Comment by pimato** [comment]
My env. file
```
REACT_APP_VERSION=omen
REACT_APP_INFURA_PROJECT_ID="xxx"
REACT_APP_MARKET_FEE=2.00
REACT_APP_GRAPH_MAINNET_HTTP='https://api.thegraph.com/subgraphs/name/gnosis/omen'
REACT_APP_GRAPH_MAINNET_WS='wss://api.thegraph.com/subgraphs/name/gnosis/omen'
REACT_APP_GRAPH_RINKEBY_HTTP='https://api.thegraph.com/subgraphs/name/gnosis/omen-rinkeby'
REACT_APP_GRAPH_RINKEBY_WS='wss://api.thegraph.com/subgraphs/name/gnosis/omen-rinkeby'
```

Network: Rinkeby

when trying to create a market the UI signals me that I am earning 4% trading fees:
<img width="603" alt="Screenshot 2020-06-08 at 23 13 42" src="https://user-images.githubusercontent.com/5337809/84081169-c3703a00-a9dd-11ea-831f-3f89403d4228.png">
