### ISSUE TITLE
New Market Overview Widget 

### ISSUE THREAD

**Issue by pimato** [protofire/gnosis-conditional-exchange#802]
With the new dropdown navigation for Market Category and State comes a new Market Overview widget. 

**Current:**
<img width="834" alt="market overview-old" src="https://user-images.githubusercontent.com/5337809/84500537-0d467200-acb5-11ea-976f-2afac6570764.png">

**Version 2:**
<img width="834" alt="market overview" src="https://user-images.githubusercontent.com/5337809/84500584-251df600-acb5-11ea-90a7-8439a880ae86.png">

**Deliverables:**
- Replace the `Load more - Button` with a pagination where `right-arrow` loads `4 new items`
- Add a dropdown picker to let the user decide how many markets he want to see (this could be stored on the browser cache)
- Add a `Markets - Header Title` to the widget
- Polish the new list item designs:
    - Replace `Top Outcome:` with the star icon to indicate which outcome is leading
    - replace `Ends in time` to  `time remaining`
    - the third market details should always be the metric which the user picked in the `Sort by - Dropdown`
    - Improve the current `Sort by [metric type]` where the user actually sees what picked metric is

**Figma:**
[Design Specification](https://www.figma.com/file/R056tSYMjvfwaFidEBItYy/Widgets-V2?node-id=1%3A953)

**Estimated Time:**
8h

Total Bounty:
**320$** (8h * 40$ per hour)
**600 REP (~0.05%)** DXdao reputation

**ATTENTION: The estimated time and bounty is just my personal estimations and are not a officially ratified by the collective. Feel free propose a different estimate/bounty**

**Comment by KadenZipfel** [comment]
I'll take this on.

**Comment by KadenZipfel** [comment]
https://github.com/protofire/gnosis-conditional-exchange/pull/860
