### ISSUE TITLE
Automatically add a week to the resolution date

### ISSUE THREAD

**Issue by clesaege** [protofire/gnosis-conditional-exchange#831]
It looks like a lot of people are putting the resolution date of markets referring to a period to the last day of a period. See example there:
https://gateway.ipfs.io/ipfs/QmbB3wA5R2PR8s87pJRSUCcBHRxAtfFtkSWmVWEcHsaFeV/#/0x578003b0785f32a2ca3b307059181f5c0514438a
This result in ending dates before the event is known thus markets resolving as invalid.
We can automatically add 1 week to the resolution date at the UI level to avoid this and also avoid cases where the information is not directly available.

**Comment by pimato** [comment]
I don`t think everyone should get forced to add 7 days to its market. We are going to try tell it the user for now only:
https://github.com/protofire/gnosis-conditional-exchange/issues/841
